[project]
name = "Pixlr"
version = "0.1.2"
description = "An app for drawing pixel arts"
readme = "README.md"
requires-python = "==3.12.10"
dependencies = [
    "pillow>=11.2.1",
    "pygame>=2.6.1",
]
